version: "3"
services:
  apachephp:
    restart: always
    # build: ./
    # image: rwweb
    image: jhalbrecht/rwweb:0.7 # pull it from docker hub. :-)
    depends_on:
      - mariadb
    container_name: rightweight
    ports:
      - '8080:80'
    links:
      - mariadb
    networks:
      - rw-docker

  mariadb:
    hostname: rwdb
    image: mariadb
    restart: always
    container_name: rwdb
    environment:
      TZ: "${TZ:-UTC}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-deePhaultDB}"
      MYSQL_USER: "${MYSQL_USER:-deePhaultUser}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-deePhaultPW}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD:-0}"
      # MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-SecRet}"

    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    networks:
      - rw-docker



  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    ports:
      - 8001:80
    links:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - rw-docker
networks:
  rw-docker:
    driver: bridge